logging:
  config: classpath:log4j2.xml
spring:
  main:
    web-application-type: NONE

jms:
  rabbit-mq:
    host: "localhost"
    port: 5672
    virtual-host: "user"
    username: "user"
    password: "user"
    exchange-input-name: "userinput"
    queue-input-name: "inputqueue"
    queue-output-invoice-name: "outputinvoice"
    queue-output-order-name: "outputorder"